name: Garden Linux default package build pipeline

on:
  workflow_call:
    inputs:
      source_name:
        required: true
        type: string
jobs:
  source:
    runs-on: ubuntu-latest
    steps:
      - name: "Source " 
        run: echo "Source name is ${{ source_name }}"
